### PR TITLE
Add table to readme with links to directly open notebooks in GH, Colab, Binder

### PR DESCRIPTION
**Pull request by janosh**
Before vs after

Screen Shot 2022-08-31 at 21 29 00

### CODE REVIEW

**Comment by mkhorton** [comment]
This is beautiful! Is `Colab` fully supported; I thought it was limited to Python 3.7?

**Comment by shyuep** [comment]
Thanks. Colab works for most stuff. It will just install the latest pymatgen compatible with py37 (2022.0.x).

**Comment by janosh** [comment]
@mkhorton Should we add such a table to the crystaltoolkit readme linking to all the example apps?

**Comment by mkhorton** [comment]
Think that's a great idea :)

**Pull request merged**
